// Convert tree to Markdown
export function treeToMarkdown(tree) {
  let md = `# ${tree.title}\n\n`

  if (tree.description) {
    md += `${tree.description}\n\n`
  }

  md += `---\n\n`
  md += nodeToMarkdown(tree.root_node, 1)
  md += `\n---\n\n`
  md += `*Generated by Prompt Factory AI*\n`
  md += `*Version: ${tree.version} | Created: ${formatDate(tree.metadata.created_at)}*\n`

  return md
}

function nodeToMarkdown(node, level) {
  // Skip root node title if it's just "Root"
  const showTitle = node.title !== 'Root' || level > 1

  let md = ''

  if (showTitle) {
    const heading = '#'.repeat(Math.min(level + 1, 6))
    md += `${heading} ${node.title}\n\n`
  }

  if (node.content && node.content.trim()) {
    md += `${node.content}\n\n`
  }

  if (node.examples && node.examples.length > 0) {
    md += `**Examples:**\n`
    node.examples.forEach(example => {
      md += `- ${example}\n`
    })
    md += '\n'
  }

  node.children.forEach(child => {
    md += nodeToMarkdown(child, level + 1)
  })

  return md
}

// Convert tree to JSON (pretty printed)
export function treeToJSON(tree) {
  return JSON.stringify(tree, null, 2)
}

// Parse JSON to tree
export function jsonToTree(jsonString) {
  try {
    const parsed = JSON.parse(jsonString)
    // Validate structure
    if (!parsed.id || !parsed.title || !parsed.root_node) {
      throw new Error('Invalid tree structure')
    }
    return { success: true, tree: parsed }
  } catch (error) {
    return { success: false, error: error.message }
  }
}

// Format date for display
function formatDate(isoString) {
  return new Date(isoString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}

// Download helper
export function downloadFile(content, filename, type = 'text/plain') {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
